---
title: "20191113"
author: "曾雨晴"
date: "11/13/2019"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
library(sf)
```
###CH5
##5.5.1
```{r}
point <- st_point(
  c(2,3)
)

point %>% ggplot()+geom_sf()
```
```{r}
mpoint <- st_multipoint(
    rbind(c(1,0),
        c(2,3),
        c(-1,2))
)

mpoint %>% ggplot()+geom_sf()
```
```{r}
line <- st_linestring(
    rbind(c(1,0),
        c(2,3),
        c(-1,2))
)
line %>% ggplot()+geom_sf()
```
```{r}
mline <- st_multilinestring(
  list(
    rbind(
      c(1,0),
      c(2,3),
      c(-1,3)),
    rbind(
      c(-2,3),
      c(-1,-1))
    )
  )

mline %>% ggplot()+geom_sf()
```
```{r}
outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it
  
poly <- st_polygon(
  list(
    outer, #最外圍要放在第一個
    hole
  )
) 

poly %>% ggplot()+geom_sf()
```
```{r}
outer2 <- outer + 12
hole2 <- hole + 12

mpoly <- st_multipolygon(
  list(
    list(
      outer,
      hole
    ),
    list(
      outer2,
      hole2
    )
  )
) 

mpoly %>% ggplot()+geom_sf()
```
```{r}
st_geometrycollection(
  list(
    point, mpoint,
    line, mline,
    poly, mpoly
  )
) %>% ggplot()+ geom_sf()
```
##5.5.2
```{r}
sfg_county1 <- st_polygon(list(
  outer,hole
))
sfg_county2 <- st_polygon(list(
  outer2, hole2
))

#sfg堆成sfc
sfc_county12column <- st_sfc(sfg_county1,sfg_county2)

sfc_county12column %>% ggplot+geom_sf()
```
```{r}
#設定CRS
sfc_county12column %>%
  st_set_crs(4326) -> # EPSG: 4326
  sfc_county12column
```
##5.5.3
```{r}
#各county的資料
df_county12 <- data.frame(
  name=c("county1","county2"),
  population=c(100,107)
)
df_county12
```

```{r}
#df添加geometry column
df_county12 %>%
  st_set_geometry(sfc_county12column) -> df_county12

df_county12 %>% names
```

```{r}
df_county12%>%
  ggplot+geom_sf(aes(fill=population))+
  geom_sf_text(
    aes(
      label=name
      )
  )
```

```{r}
df_county12
```

```{r}
dir.create("county12")
write_sf(df_county12,"county12/county12.shp")
```
#中和新蘆線
```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```

```{r}
sf_mrt_tpe%>%
  filter(
    stringr::str_detect(經過路線,"BL")
  )->
  sf_mrt_tpe_bl
```

```{r}
sf_mrt_tpe_bl%>%
  st_coordinates()%>%#取出點的座標，出來就是矩陣
  st_linestring()->sfg_mrt_bl
```

```{r}
sfg_mrt_bl%>%
  ggplot()+geom_sf()
```
```{r}
sf_mrt_tpe_bl%>%
  mutate(
    站號=stringr::str_extract(
      經過路線,"(?<=(BL))[:digit:]+"#取BL後面的數字不管幾位
    )
  )%>%
  arrange(站號)->sf_mrt_tpe_bl_arrange
```

```{r}
sf_mrt_tpe_bl_arrange%>%
  st_coordinates()%>%#取出點的座標，出來就是矩陣
  st_linestring()->sfg_mrt_bl_arrange #捷運板南線的simple feature geometry

sfg_mrt_bl_arrange%>%
  ggplot()+geom_sf()
```
```{r}
df_mrt <-data.frame(
  linename="BL"
)

sfg_mrt_bl_arrange%>%
  st_sfc() -> sfc_mrt_bl_arrange

df_mrt %>%
  st_set_geometry(sfc_mrt_bl_arrange) -> 
  df_mrt
df_mrt
```

```{r}
sf_mrt_tpe %>%
  st_crs -> mrt_crs
df_mrt %>%
  st_set_crs(mrt_crs) ->
  df_mrt
df_mrt
```
##5.6
```{r}
sf_county12=read_sf("county12/county12.shp")
```

```{r}
sf_taiwan=read_sf("mapdata201907311006/COUNTY_MOI_1080726.shp")

sf_taiwan%>%
  ggplot()+geom_sf()
```

