---
title: "20191023"
author: "曾雨晴"
date: "10/23/2019"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

####How to relicate

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_005.Rda?raw=true"))
c('area','age','性別','n')->names(graphdata[[1]])
## ----graph, echo=T, eval=T-----------------------------------------------
library(ggalluvial)
#is_alluvia_form(as.data.frame(graphdata), axes = 1:3, silent = TRUE)
finalplot<-ggplot(as.data.frame(graphdata),
  aes(y = n, axis1 = age, axis2 =area)) +
  geom_alluvium(aes(fill=性別), width = 1/10) +
  geom_stratum(width = 1/10, fill = "gray", color = "white") +
  geom_label(stat = "stratum", label.strata = TRUE) +scale_x_discrete(limits = c("age", "area"), expand = c(.1, .1)) +scale_fill_brewer(type = "qual", palette = "Set2")+
ggtitle("2018年登革熱病例統計")+ylab('確診人數')+theme(title = element_text(family ="QYuan" ))
finalplot                                                                                           
```

```{r}
library(readr)
library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")
```

```{r}
library(readr)
library100_102 <- read_csv("https://www.dropbox.com/s/wuo5o6l55lk68l6/library100_102.csv?dl=1")

graphList <- list()
library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102

library100_102 %>%
  filter(
    借閱日期 %>% between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=讀者年級
    )-> library2014 
```

```{r}
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T),
    讀者年級=reorder(讀者年級,讀者年級, order=T)
  ) -> library2014

library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```
###4.2 stat function
```{r}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院) # 預設 stat="count"
  )

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院), 
    geom="bar" # geom_bar內訂會取 count來當y
  )

#可以先設定用甚麼圖，也可以先算需要的資料，畫出來應該是一樣的
#stat_count是算每個x值，所以x是必須要給定的(aes(x=))
```
##要取出compute variable可以用stat(<compute variable>)或..<compute variable>..
```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop)), 
    geom="bar" # geom_bar內訂會取 count來當y
  )

#設定大家同group
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop),group="全校"), 
    geom="bar" # geom_bar內訂會取 count來當y
  )

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院,y=stat(prop),group="全校") # 預設 stat="count"
  )
```

