---
title: "課堂練習"
author: "曾雨晴"
date: "10/02/2019"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)
font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

#Chapter8

### 8.1.4 save as svg
```{r}
load(url("https://www.dropbox.com/s/r21jg0vxf77geu9/plot_tree.Rda?dl=1"))

plot_tree

ggsave(plot_tree, file="plot_tree1.svg")
```

####8.3.1.1

```{r}
source("https://www.dropbox.com/s/wlv1ssxqq6n4p7u/gg_hw5_004.R?dl=1", encoding = "utf-8")
```

```{r}
gg_hw5_004 %>%
  ggplotly() ->
  pltly_hw5_004
pltly_hw5_004
```

```{r}
#file.create(".Rprofile")
#file.edit(".Rprofile") 
```

```{r}
#檢查確定rproject是否有資料
Sys.getenv("plotly_username")
Sys.getenv("plotly_api_key")
```

```{r}
api_create(pltly_hw5_004,filename="pltly_hw5_004",fileopt="overwrite") -> Meta_pltly_hw5_004
```

```{r}
pltly_hw5_004_v1b<-api_download_plot("1","sunnyzeng")
pltly_hw5_004_v1b
```

```{r}
graphdata<-list()

pltly_hw5_004_v1b<-graphdata$graph
save(graphdata,file = "graph.Rda")
```

####8.3.4.1
```{r}
p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
   geom_point() + geom_smooth()
pltly_p0 <- ggplotly(p)

pltly_p0
```
#####8.3.4.1.1 json
```{r}
pltly_p0%>% plotly_json()
```
######8.4.3.1.2
```{r}
pltly_p <- 
  pltly_p0 %>% 
  style(
    traces=2:3,
    hoverinfo = "none" ### 不顯示
    ) 

pltly_p %>% layout(
  title="hovertext='none' on traces 2-3"
)
```

