---
title: "20191009"
author: "曾雨晴"
date: "10/02/2019"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
```

```{r}
library(readr)
disposableIncome <- read_csv("https://www.dropbox.com/s/z80sbjw94cjex8x/disposableIncome.csv?dl=1")
disposableIncome_gather <- read_csv("https://www.dropbox.com/s/cdw1f10jow4frxb/disposableIncome_gather.csv?dl=1")
```

```{r}
c('X1','平均每戶可支配所得','可支配所得按戶數五等分位組-最低所得組','可支配所得按戶數五等分位組-次低所得組','可支配所得按戶數五等分位組-中間所得組','可支配所得按戶數五等分位組-次高所得組','可支配所得按戶數五等分位組-最高所得組') -> names(disposableIncome)
c('年','平均每戶可支配所得','所得組距','可支配所得') -> names(disposableIncome_gather)
```

```{r}
disposableIncome %>%
  mutate(
    年=as.integer(X1)
  ) -> disposableIncome

disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="dashed")
```

```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="33")
```

```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype='2451')
```
```{r}
library(magrittr)
disposableIncome_gather$所得組距 %<>%
  factor(levels=c(
    "可支配所得按戶數五等分位組-最低所得組",
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組",
    "可支配所得按戶數五等分位組-最高所得組"
  )) 
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距,size=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71")
  ) +
  scale_size_manual(
    values=c(0.1,0.3,0.3,0.5,0.7)*1.5
  ) -> p_linetype
p_linetype
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_014.Rda?raw=true"))

```

```{r}
c('年','地區','來台旅遊人數') -> names(graphData$travelerFromAsia)
graphData
graphData$travelerFromAsia%>%
  mutate(
    年=as.numeric(年)
  )->graphData$travelerFromAsia
```


```{r}
graphData$travelerFromAsia%>%
  ggplot(aes(x=年,y=來台旅遊人數,color=地區))+
  geom_line(
    aes(linetype=地區)
  )+
  scale_linetype_manual(
    values=c("15","24","34","51","71","33","1242")
  ) -> travelerFromAsia_linetype
travelerFromAsia_linetype
```

```{r}
dataCPI <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/PR0101A2Mc.csv", 
    locale = locale(encoding = "BIG5"), skip = 3)

## 改變數名稱
dataCPI %>% 
  dplyr::rename(
    年月=X1,
    CPI=原始值
  ) -> dataCPI

# 移除「有NA」的row
dataCPI %>% na.omit() -> dataCPI

## 調整class
dataCPI$年月 %>% str_c("/01") %>% #擴增為YMD表示
  ymd() -> dataCPI$年月

# 改成2003M1為基期,其指數為100
dataCPI %>% filter(年月==ymd("2003-01-01")) %>% 
  select(CPI) -> CPI2003M1
dataCPI %>% 
  mutate(CPI=CPI/CPI2003M1$CPI*100) -> dataCPI2
```
```{r}
dataCPI2 %>% ggplot()+
  geom_line(aes(x=年月,y=CPI)) -> basePlot2
basePlot2
```

```{r}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA))

basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA))+
  scale_y_continuous(limits=c(80,NA)) #選出想要的範圍
```

```{r}
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71"),
    limits=c(
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組")
  )
#limit挑出想要展現的資料
```

```{r}
breakDates <- c("2003-01-01",
                "2005-01-01","2010-01-01","2015-01-01",
                "2018-01-01")
breakDates %>% ymd() -> breakDates
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates)
#break可以挑出想說明的點
```

```{r}
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71"),
    breaks=c(
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組")
  )

#limit 只會展現出三條線
#break 會展現出全部，但只會說明三條
```

```{r}
breakDates <- c("2003-01-01",
                "2005-01-01","2010-01-01","2015-01-01",
                "2018-01-01")
breakDates %>% ymd() -> breakDates

breakLabels <- c("2003",
                 "2005","2010","2015",
                 "2018")
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = breakLabels)
#先用break挑出要展現的點，再用label改成要展現的字
```

```{r}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = function(x) year(x))
```

```{r}
breakLabel_fun<-function(x){
  as.character(year(x)-1911)
}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = breakLabel_fun)
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = function(x) year(x)-1911)

```

```{r}
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71"),
    breaks=c(
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組"),
    labels=c(
    "次低所得組",
    "中間所得組",
    "次高所得組"),
    )
```

```{r}
disposableIncome_gather %>%
  group_by(所得組距) %>% #依照所得組距
  summarise(
    最後一年=last(年),
    可支配所得=last(可支配所得)
  ) %>%
  ungroup() %>%
  mutate(
    所得組=stringr::str_replace(
      as.character(所得組距),"可支配所得按戶數五等分位組-","")
    #把可支配所得按戶數五等分位組取代成空白
    )-> disposableIncome_gather_legend

disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71"),
    breaks=c(
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組")
    ) +
  theme(legend.position = "none") + # 取消legend
  geom_text(
    data=disposableIncome_gather_legend,
    aes(
      x=最後一年,
      y=可支配所得,
      label=所得組
    ),
    nudge_x= -3.8, size=3 #size是字的大小，nudge_x減3.8，往左移
  )
```

```{r}

library(scales)
library(colorspace)
library(shiny)
library(shinyjs)

## Register custom color palette
colorspace::sequential_hcl(n = 7, h = 360, c = c(92, NA, NA), l = c(80, 96), power = 1.05, rev = TRUE, register = "Palette")->c1
show_col(c1)
graphData$Case_10_result %>% 
  ggplot(
    aes(
      x = 六都, 
      y = `同意比例（同意票／有效票）`
    )
  ) + 
  geom_col(
    aes(
      fill = 六都, 
      width = 0.5
    )
  ) + 
  coord_flip() + #轉軸
   scale_y_continuous(
    limits = c(0, 0.8), 
    labels = percent_format()
  ) + 
  labs(
    title = "你是否同意民法婚姻規定應限定在一男一女的結合 ?"
  ) + 
  scale_fill_discrete_qualitative(
    palette = "god-Palette-Qualitative1", 
    nmax = 6
  ) + 
  geom_text(
    aes(
      label = str_c(
        round(`同意比例（同意票／有效票）`*100, 1), 
        "%"
      )
    ), 
    size = 10
  ) + 
  theme(
    plot.title = element_text(
      colour = "black", face = "bold", 
      size = 35 
    ), 
    axis.title.x = element_text(face = "bold", size = 25), 
    axis.title.y = element_text(face = "bold", size = 25), 
    axis.text.x = element_text(size = 20), 
    axis.text.y = element_text(size = 20), 
    legend.position = "none"
  )
```

```{r}
library(scales)
library(colorspace)
library(shiny)
library(shinyjs)
choose_palette(gui = "shiny")
```


