---
title: "課堂練習"
author: "曾雨晴"
date: "10/02/2019"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

####作業
##整理資料、繪圖、說明
將整理好的資料存在graphData
將graphDate存成list()
將最後的圖存成finalplot
##將plot轉成ggplotly
finalplot %>%
  ggplotly()
可以變成互動式，知道圖每個點的數值
##存成一個檔案
引入資料(1個或數個)
save(bop_aq,boq_aa,...., file="uploadfile.Rda")
load("uplodfile.Rda")

```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
```
####3.1 顏色
###3.2.1 顏色模型
##RGB
```{r}
library(grDevices)
rgb(0,0,1) # 即對應顏色強度(0,0,255) #每個顏色皆是0-1
```

```{r}
rgb(0.5,0,0.7) # 即對應顏色強度(0.5*255,0,0.7*255)進位到整數
```

```{r}
library(scales)
show_col(c(rgb(0,0,1),rgb(0.5,0,0.7)))
show_col(c(rgb(0,0.5,0.6),rgb(0.8,0.5,0.5)))
```
##HSV
```{r}
show_col(
  c(
    hsv(30/360,0,0),hsv(30/360,0.5,0),hsv(30/360,1,0), # (,,lightness=0) 全暗
    hsv(30/360,0,0.5),hsv(30/360,0.5,0.5),hsv(30/360,1,0.5), # (,,lightness=0.5)
    hsv(30/360,0,1),hsv(30/360,0.5,1),hsv(30/360,1,1) # (,,lightness=1) 全亮
  )
)
```
##HCL
```{r}
choose_color()
```

```{r}
show_col("#6E94BA")
```
###3.1.3 調色盤palette
```{r}
choose_palette(gui="shiny")
```


```{r}
## Register custom color palette
colorspace::sequential_hcl(n = 8, h = 260, c = c(80, NA, NA), l = c(30, 90), power = 1, register = "MyBluePlatte")
basicBoxplot+
  scale_fill_discrete_sequential(palette = "MyBluePlatte")

colorspace::sequential_hcl(n = 7, h = c(-71, 161), c = c(81, NA, 28), l = c(34, 98), power = c(0.4, 1.3), register = "PracticePalette")
colorspace::qualitative_hcl(n = 7, h = c(-97, 355), c = 40, l = 86, register = "P2")
basicBoxplot+
  scale_fill_d iscrete_qualitative(palette = "P2")
basicScatterPlot+
  scale_color_continuous_qualitative(palette = "P2")
```

```{r}
pal_qual <- colorspace::qualitative_hcl(
  n = 7, 
  h = c(0, 360), c = 35, l = 85, 
  register = "myQualitative"
  )
pal_qual %>% specplot(hcl=F)
```


```{r}
pal_seq <- colorspace::sequential_hcl(
  n = 7, 
  h = 135, c = c(45, NA, NA), l = c(35, 95), 
  power = 1.3, 
  register = "mySequential")
pal_seq %>% specplot(hcl=F)
```
```{r}
pal_diverge <- colorspace::diverging_hcl(
  n = 7, 
  h = c(260, 0), c = 80, l = c(30, 90), 
  power = 1.5, 
  register = "myDiverge")
pal_diverge %>% specplot(hcl=F)
```

```{r}
## Register custom color palette
colorspace::diverging_hcl(n = 7, h = c(260, 0), c = 80, l = c(30, 90), power = 1.5, register = "Custom-Palette")->redblue

data.frame(
  x1 = factor(sample(c(1L,2L,3L),100,replace=T)),
  x2 = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = factor(sample(letters[1:4],100,replace=T))
) -> df_example

df_example %>%
  ggplot()+
  geom_boxplot(
    aes(x=x1,y=y,fill=z2)
  ) -> basicBoxplot
basicBoxplot

df_example %>%
  ggplot()+
  geom_point(
    aes(x=x2,y=y,color=z1)
  ) -> basicScatterPlot
basicScatterPlot

basicBoxplot +
  scale_fill_discrete_qualitative(palette="myQualitative",nmax=5) # 由於色圈會由0度出發回到360度所以第1個及第5個會是同色，因此4類要創出5個顏色才不會有1,4類同色問題。
basicScatterPlot +
  scale_color_continuous_sequential(palette = "mySequential")
basicScatterPlot +
  scale_color_continuous_diverging(palette="myDiverge")
```

```{r}
basicBoxplot+
  scale_fill_brewer(palette = "Dark2")
#不用寫type
```
```{r}
basicScatterPlot+
  scale_color_distiller(palette = "Set1")

```

