---
title: "課堂練習"
author: "曾雨晴"
date: "10/09/2019"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
```

```{r}
library(readr)
disposableIncome <- read_csv("https://www.dropbox.com/s/z80sbjw94cjex8x/disposableIncome.csv?dl=1")
disposableIncome_gather <- read_csv("https://www.dropbox.com/s/cdw1f10jow4frxb/disposableIncome_gather.csv?dl=1")
```

```{r}
c('X1','平均每戶可支配所得','可支配所得按戶數五等分位組-最低所得組','可支配所得按戶數五等分位組-次低所得組','可支配所得按戶數五等分位組-中間所得組','可支配所得按戶數五等分位組-次高所得組','可支配所得按戶數五等分位組-最高所得組') -> names(disposableIncome)
c('年','平均每戶可支配所得','所得組距','可支配所得') -> names(disposableIncome_gather)
```

```{r}
disposableIncome %>%
  mutate(
    年=as.integer(X1)
  ) -> disposableIncome

disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="dashed")
```

```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="33")
```

```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype='2451')
```
```{r}
library(magrittr)
disposableIncome_gather$所得組距 %<>%
  factor(levels=c(
    "可支配所得按戶數五等分位組-最低所得組",
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組",
    "可支配所得按戶數五等分位組-最高所得組"
  )) 
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距,size=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71")
  ) +
  scale_size_manual(
    values=c(0.1,0.3,0.3,0.5,0.7)*1.5
  ) -> p_linetype
p_linetype
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_014.Rda?raw=true"))
graphData
```





