---
title: "課堂練習20190925"
author: "曾雨晴"
date: "9/25/2019"
output: html_notebook
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","C:/Users/User/Downloads/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

####gather and spread
### gather
```{r}
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),#如果要用數字開頭就要用反頓點
  `2000`=c("2k","80k","213k"),
  check.names = F
)

df_gatherExample
```
##將collegeData裡各年級男女生人數合成兩個欄位，類別,人數，其中類別值為原始欄位名稱（即一年級男生，一年級女生，…等等），而人數則為對應人數。
```{r}
df_gatherExample
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口")->df_gatherExample
```

```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```

```{r}
collegeData%>%
  gather(
  contains("生"),
  key="類別",value="人數")->collegeDataGather
```
##桃園各地區每月結婚對數：
```{r}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")
```
#將資料「一～十二月」縮排在月份變數，而其下的對應值縮排在對數變數。
```{r}
df_taoyuanMarriage%>%
  gather(
    ends_with("月"),
    key="月份",value="對數"
  )->df_taoyuanMarriageGather
```
#計算每個月份桃園總結婚對數。
```{r}
df_taoyuanMarriageGather%>%
  group_by(月份)%>%
  summarise(
    總結婚對數=sum(對數)
  )->df_taoyuanMarriageGather_all
#可以用mutate_at
```
#找出每個地區結婚最高峰月份。
```{r}
df_taoyuanMarriage%>%
gather(
       ends_with("月"),
       key="月份",value="對數"
      )%>%group_by(月份區域別)%>%summarise(結婚最高峰月份=which.max(對數))
```


##spread
```{r}
df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朶萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))
```

```{r}
df_spreadExample
spread(df_spreadExample,
       var,value)->df_spreadExample_spread
```

```{r}
collegeDataGather %>%
  spread(
    類別,人數
  )->collegeDataGather_spread
```

```{r}
df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")
```
```{r}
df_twbankExchangeRate%>%
  select(-即期賣出匯率)%>%
  spread(
    幣別,即期買入匯率
  )->df_twbankExchangeRate_spread
```

####變數類別調整
```{r}
df_twbankExchangeRate%>%
  mutate(
    幣別=as.factor(幣別),
    即期買入匯率=as.double(即期買入匯率),
    即期賣出匯率=as.double(即期賣出匯率),
    日期=lubridate::ymd(日期)
  )
```

####Data import
```{r}
library(readr); library(dplyr)
# 線上引入原始資料成字串向量
read_lines("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates") ->
  originalLines

# 將字串由CP950編碼改成UTF8再讀成data frame data2
originalLines %>%
  iconv(from="CP950",to="UTF8") %>% 
  read_csv() -> data2
```

```{r}
taifex_open_data <- read_csv("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates",locale = locale(encoding = "BIG5"))
```

```{r}
taifex_open_data%>%
  mutate(
    日期=lubridate::ymd(日期)
  )->taifex_open_data
  
```

```{r}
ODwsvTravelFood <- read_csv("http://data.coa.gov.tw/Service/OpenData/ODwsv/ODwsvTravelFood.aspx?FOTT=CSV", 
    locale = locale())
```

```{r}
A53000000A_000041_003 <- read_csv("https://lod2.apc.gov.tw/API/v1/dump/datastore/A53000000A-000041-003")
```

```{r}
f1531986463137 <- read_csv("https://www.sa.gov.tw/wSite/public/Data/f1531986463137.csv")
```

```{r}
X108_E5_B9_B4_E5_9C_8B_E4_B8_AD_E6_95_99_E8_82_B2_E6_9C_83_E8_80_83_E5_90_84_E7_A7_91_E8_A9_A6_E9_A1_8C_E9_80_9A_E9_81_8E_E7_8E_87 <- read_csv("https://www.k12ea.gov.tw//files/common_unit/b4929928-1f9b-4c48-98e6-2acfd0f7b27d/doc/108%E5%B9%B4%E5%9C%8B%E4%B8%AD%E6%95%99%E8%82%B2%E6%9C%83%E8%80%83%E5%90%84%E7%A7%91%E8%A9%A6%E9%A1%8C%E9%80%9A%E9%81%8E%E7%8E%87.csv", 
    locale = locale())
```

```{r}
library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")
```

```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )

#pipe寫法
subsetDataTWbank%>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
#點
subsetDataTWbank%>%
  ggplot()+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
#線加點
subsetDataTWbank%>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
#把aes提出
ggplot(subsetDataTWbank,
       aes(x=西元年月,y=`定存利率-一個月-固定`))+
  geom_line()+
  geom_point()
```
#請由subsetDataTWbank產生以下圖示：其中

#座標對應：x=定存類型, y=利率

#幾何圖示類型：boxplot
```{r}
subsetDataTWbank%>%
  gather(
    contains("定存"),
    key=定存類型,value=利率
  )%>%
  ggplot()+
  geom_boxplot(
    aes(x=定存類型,y=利率)
  )

#中線Q2=中位數 Q1,Q2,Q3 上下1.5倍 剩下的點是outliers
```

```{r}
subsetDataTWbank%>%
  gather(
    contains("定存"),
    key=定存類型,value=利率)->subsetDataTWbank_gather

subsetDataTWbank_gather %>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=利率,color=定存類型)
  )
```

```{r}
subsetDataTWbank%>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`),
    color="red",
    alpha=0.2, 
    size=2
  )
#color可以用文字描述
#alpha通透度,連續變數，不能用在間斷資料
#size粗細
```
####字串變數
###查看目前levels出現順序：
```{r}
subsetDataTWbank_gather$定存類型 %>% 
  as.factor %>% levels
```
###改變levels出現順序：
```{r}
subsetDataTWbank_gather %>%
  mutate(
    定存類型=factor(定存類型,levels=c("定存利率-一個月-固定","定存利率-二年期-固定","定存利率-三年期-固定"))
  ) -> subsetDataTWbank_gather

subsetDataTWbank_gather %>%
  ggplot()+
  geom_boxplot(aes(x=定存類型,y=利率))
```
###時間資料
```{r}
twCalendar <- c("民國88年11月1日","民國88年12月1日","民國89年1月1日")
```
##民國轉成西元
```{r}
twCalendar %>%
  # 取出字串中的數字部份
  stringr::str_extract_all("[:digit:]+") %>%
  # 將每個日期的「年」數字加上1991再合併年月日成為`yyyy-mm-dd`格式
  purrr::map_chr(
             function(x) {
               x1=as.integer(x[[1]])+1911
               x[[1]]=as.character(x1)
               stringr::str_c(x,collapse="-")
             }
             ) -> westernCalendar

westernCalendar %>%
  lubridate::ymd() -> datetimeCalendar
class(datetimeCalendar)
```

```{r}
subsetDataTWbank %>%
  mutate(
    年月=年月 %>%
      stringr::str_extract_all("[:digit:]+") %>% # 取出字串中的數字部份
      purrr::map_chr(
                 function(x) {
                   x1=as.integer(x[[1]])+1911# 將每個日期的「年」數字加上1991
                   x[[1]]=as.character(x1)
                                stringr::str_c(x,collapse="-")#將年月連接
                 }
                 ),
    年月日=stringr::str_c(年月,"01",sep="-"),#加上日
    西元年月日=lubridate::ymd(年月日)
  )
```

