---
title: "範本"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: ['css/mystyle.css']
    includes:
      in_header: ["external/in_header/header.html"]
      before_body: ["external/before_body/bf_body.html"]
      after_body: ["external/after_body/af_body.html"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(sf); library(osmdata); library(rmapshaper); library(htmlwidgets); library(widgetframe); library(htmltools)
library(spData); library(colorspace)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
#theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

