---
title: "UFO Activities"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: readable
---

```{r setup, include=FALSE}
library(flexdashboard)
```
<!--"journal","readable","paper"-->


All
==================================================================

Column {data-width=500}
------------------------------------------------------------------

### All

```{r}
load("graphData.Rda")
graphData$mock_ufo_data_date_raster
```

Column {.tabset data-width=500}
------------------------------------------------------------------
### Facebook

```{r}
graphData$mock_ufo_data_facebook
```

### Poster

```{r}
graphData$mock_ufo_data_poster
```

### Website

```{r}
graphData$mock_ufo_data_website
```

北大玩具節
==================================================================

Column {data-width=500}
------------------------------------------------------------------
### All


```{r}

```

Column {.tabset data-width=500}
------------------------------------------------------------------
### Facebook

```{r}

```

### Poster

```{r}

```

### Website

```{r}

```

青銀共賞電影
==================================================================

Column {data-width=500}
------------------------------------------------------------------
### All

```{r}

```

Column {.tabset data-width=500}
------------------------------------------------------------------
### Facebook

```{r}

```

### Poster

```{r}

```

### Website

```{r}

```

聖誕點燈暨北大管樂節
==================================================================

Column {data-width=500}
------------------------------------------------------------------
### All

```{r}

```

Column {.tabset data-width=500}
------------------------------------------------------------------
### Facebook

```{r}

```

### Poster

```{r}

```

### Website

```{r}

```

